language: ruby
sudo: false
rvm:
- 2.2.3
cache:
  bundler: true
env:
- DB=pgsql
services:
- postgresql
before_script:
- cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
- psql -c 'create database lodestar_test' -U postgres
script:
- bundle exec rake
branches:
  only:
  - master
  - development
